-- ARQUIVO PRIVADO: contém o gabarito. NÃO envie para repositório público.
-- Execute uma vez no SQL Editor do Supabase.

insert into public.activities (code, title, active)
values ('AULA01-SISTNUM', 'Aula 01 — Sistemas Numéricos', true)
on conflict (code) do update set title = excluded.title, active = excluded.active;

insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q01', 'AULA01-SISTNUM', 1, 'Conceitual', 'Quais símbolos podem aparecer em um número binário?', '["0 e 1", "0 a 7", "0 a 9", "0 a 9 e A a F"]'::jsonb, '0 e 1', 'O sistema binário é de base 2 e utiliza apenas os símbolos 0 e 1.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q02', 'AULA01-SISTNUM', 2, 'Conceitual', 'No sistema hexadecimal, qual é o valor decimal do símbolo F?', '["10", "14", "15", "16"]'::jsonb, '15', 'No hexadecimal, A=10, B=11, C=12, D=13, E=14 e F=15.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q03', 'AULA01-SISTNUM', 3, 'Conceitual', 'No número decimal 410, por que o algarismo 4 representa 400?', '["Porque 4 sempre vale 400", "Porque está na posição correspondente a 10²", "Porque 410 é um número binário", "Porque a base decimal é 4"]'::jsonb, 'Porque está na posição correspondente a 10²', 'Na notação posicional decimal: 410 = 4×10² + 1×10¹ + 0×10⁰.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q04', 'AULA01-SISTNUM', 4, 'Conceitual', 'Quantos bits correspondem exatamente a um dígito hexadecimal?', '["2", "3", "4", "8"]'::jsonb, '4', 'Como 16 = 2⁴, cada dígito hexadecimal representa exatamente 4 bits.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q05', 'AULA01-SISTNUM', 5, 'Conceitual', 'Qual é o valor decimal de 10₂?', '["1", "2", "10", "16"]'::jsonb, '2', '10₂ = 1×2¹ + 0×2⁰ = 2₁₀.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q06', 'AULA01-SISTNUM', 6, 'Fácil', 'Converta 101₂ para decimal.', '["3", "4", "5", "6"]'::jsonb, '5', '101₂ = 1×2² + 0×2¹ + 1×2⁰ = 4 + 0 + 1 = 5.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q07', 'AULA01-SISTNUM', 7, 'Fácil', 'Converta 1101₂ para decimal.', '["11", "12", "13", "14"]'::jsonb, '13', '1101₂ = 8 + 4 + 0 + 1 = 13₁₀.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q08', 'AULA01-SISTNUM', 8, 'Fácil', 'Converta 10₁₀ para binário.', '["1000₂", "1010₂", "1100₂", "1110₂"]'::jsonb, '1010₂', '10 = 8 + 2 = 2³ + 2¹, portanto 10₁₀ = 1010₂.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q09', 'AULA01-SISTNUM', 9, 'Fácil', 'Converta 15₁₀ para hexadecimal.', '["E₁₆", "F₁₆", "10₁₆", "15₁₆"]'::jsonb, 'F₁₆', 'O valor decimal 15 é representado pelo símbolo F no hexadecimal.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q10', 'AULA01-SISTNUM', 10, 'Fácil', 'Qual é o valor decimal de A₁₆?', '["8", "9", "10", "11"]'::jsonb, '10', 'No hexadecimal, A representa o valor decimal 10.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q11', 'AULA01-SISTNUM', 11, 'Médio', 'Converta 25₁₀ para binário.', '["11001₂", "10101₂", "11100₂", "10011₂"]'::jsonb, '11001₂', '25 = 16 + 8 + 1, portanto 25₁₀ = 11001₂.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q12', 'AULA01-SISTNUM', 12, 'Médio', 'Converta 42₁₀ para binário.', '["101010₂", "101100₂", "110010₂", "100101₂"]'::jsonb, '101010₂', '42 = 32 + 8 + 2, portanto 42₁₀ = 101010₂.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q13', 'AULA01-SISTNUM', 13, 'Médio', 'Converta 11111111₂ para hexadecimal.', '["EF₁₆", "F0₁₆", "FF₁₆", "1FF₁₆"]'::jsonb, 'FF₁₆', 'Agrupando em blocos de 4 bits: 1111 1111 → F F.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q14', 'AULA01-SISTNUM', 14, 'Médio', 'Converta 2D₁₆ para decimal.', '["35", "43", "45", "46"]'::jsonb, '45', '2D₁₆ = 2×16¹ + 13×16⁰ = 32 + 13 = 45.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q15', 'AULA01-SISTNUM', 15, 'Médio', 'Qual é a representação binária de 3A₁₆ em grupos de 4 bits?', '["0011 1010", "0011 1100", "1010 0011", "1110 0011"]'::jsonb, '0011 1010', '3₁₆ = 0011₂ e A₁₆ = 1010₂. Logo, 3A₁₆ = 0011 1010₂.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q16', 'AULA01-SISTNUM', 16, 'Difícil', 'Converta 100101₂ para decimal.', '["35", "36", "37", "41"]'::jsonb, '37', '100101₂ = 32 + 4 + 1 = 37₁₀.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q17', 'AULA01-SISTNUM', 17, 'Difícil', 'Converta 173₁₀ para hexadecimal.', '["A9₁₆", "AB₁₆", "AD₁₆", "B1₁₆"]'::jsonb, 'AD₁₆', '173 ÷ 16 = 10 com resto 13. Em hexadecimal, 10=A e 13=D: AD₁₆.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q18', 'AULA01-SISTNUM', 18, 'Difícil', 'Converta 7B₁₆ para decimal.', '["119", "121", "123", "125"]'::jsonb, '123', '7B₁₆ = 7×16 + 11 = 112 + 11 = 123.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q19', 'AULA01-SISTNUM', 19, 'Difícil', 'Converta 10110110₂ para hexadecimal.', '["A6₁₆", "B6₁₆", "B5₁₆", "C6₁₆"]'::jsonb, 'B6₁₆', '1011 0110 → B 6. Portanto, 10110110₂ = B6₁₆.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q20', 'AULA01-SISTNUM', 20, 'Difícil', 'Qual é a representação binária de C7₁₆?', '["1100 0111", "1101 0111", "1011 0111", "1100 1110"]'::jsonb, '1100 0111', 'C₁₆ = 1100₂ e 7₁₆ = 0111₂. Logo, C7₁₆ = 1100 0111₂.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q21', 'AULA01-SISTNUM', 21, 'Desafiador', 'Qual é a representação hexadecimal de 64206₁₀?', '["FACE₁₆", "FACA₁₆", "FADE₁₆", "FCAE₁₆"]'::jsonb, 'FACE₁₆', 'FACE₁₆ = 15×16³ + 10×16² + 12×16 + 14 = 64206.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q22', 'AULA01-SISTNUM', 22, 'Desafiador', 'Converta 111010101011₂ para hexadecimal.', '["DAB₁₆", "EAB₁₆", "EAC₁₆", "FAB₁₆"]'::jsonb, 'EAB₁₆', 'Agrupando: 1110 1010 1011 → E A B.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q23', 'AULA01-SISTNUM', 23, 'Desafiador', 'Converta 2026₁₀ para hexadecimal.', '["7DA₁₆", "7EA₁₆", "8EA₁₆", "7FA₁₆"]'::jsonb, '7EA₁₆', '2026 = 7×16² + 14×16 + 10 = 1792 + 224 + 10. Logo, 7EA₁₆.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q24', 'AULA01-SISTNUM', 24, 'Desafiador', 'Qual das equivalências abaixo está INCORRETA?', '["255₁₀ = 11111111₂ = FF₁₆", "64₁₀ = 1000000₂ = 40₁₆", "31₁₀ = 11111₂ = 1F₁₆", "26₁₀ = 11010₂ = 1B₁₆"]'::jsonb, '26₁₀ = 11010₂ = 1B₁₆', '26₁₀ = 11010₂, mas em hexadecimal é 1A₁₆, e não 1B₁₆.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
insert into public.questions (id, activity_code, position, level, prompt, options, correct_answer, explanation, active) values ('Q25', 'AULA01-SISTNUM', 25, 'Desafiador', 'O valor decimal 2748 deve ser representado em binário e hexadecimal. Qual par está correto?', '["1010 1011 1100₂ e ABC₁₆", "1010 1011 1101₂ e ABD₁₆", "1011 1010 1100₂ e BAC₁₆", "1010 1100 1011₂ e ACB₁₆"]'::jsonb, '1010 1011 1100₂ e ABC₁₆', 'ABC₁₆ = 10×16² + 11×16 + 12 = 2748, e A B C → 1010 1011 1100₂.', true) on conflict (id) do update set activity_code=excluded.activity_code, position=excluded.position, level=excluded.level, prompt=excluded.prompt, options=excluded.options, correct_answer=excluded.correct_answer, explanation=excluded.explanation, active=excluded.active;
